### ISSUE TITLE
timestamp for utterance or sentence?

### ISSUE THREAD

**Issue by chenrq2005** [huggingface/distil-whisper#27]
curious if current output format of distil-whisper has timestamp for utterance or sentence. If no, will be considered in the future?

**Comment by aleksandr-smechov** [comment]
You can enable segment-level timestamps with:

`output = pipe(inputs, return_timestamps=True, batch_size=4)`

You can add word-level timestamps with the [align](https://github.com/m-bain/whisperX/blob/main/whisperx/alignment.py) function from WhisperX, but keep in mind sometimes Whisper sometimes will return `None` if the segment ends in the middle of a word. In that case just estimate the average duration per character and guess the ending timestamp.

`avg_duration_per_char = total_duration / total_characters # for None timestamp cases`

**Comment by chenrq2005** [comment]
Thanks so much!

**Comment by sanchit-gandhi** [comment]
Indeed, Distil-Whisper was trained with sentence level timestamps (same training task as Whisper), which you can enable as follows:
```python
import torch
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline
from datasets import load_dataset


device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model_id = "distil-whisper/distil-large-v2"

model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True
)
model.to(device)

processor = AutoProcessor.from_pretrained(model_id)

pipe = pipeline(
    "automatic-speech-recognition",
    model=model,
    tokenizer=processor.tokenizer,
    feature_extractor=processor.feature_extractor,
    max_new_tokens=128,
    torch_dtype=torch_dtype,
    device=device,
)

dataset = load_dataset("hf-internal-testing/librispeech_asr_dummy", "clean", split="validation")
sample = dataset[0]["audio"]

# result with no timestamps
result = pipe(sample)
print("No timestamps: ", result["text"])

# result with timestamps
result = pipe(sample, return_timestamps=True)
print("With timestamps: ", result["chunks"])
```

We also support word-level timestamps in 🤗 Transformers using the same dynamic time-warping algorithm as OpenAI's repository. Currently, this only works with batch-size of 1 using the pre-trained Whisper models:

```python
import torch
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline
from datasets import load_dataset


device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model_id = "openai/whisper-large-v2"

model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True
)
model.to(device)

processor = AutoProcessor.from_pretrained(model_id)

pipe = pipeline(
    "automatic-speech-recognition",
    model=model,
    tokenizer=processor.tokenizer,
    feature_extractor=processor.feature_extractor,
    max_new_tokens=128,
    torch_dtype=torch_dtype,
    device=device,
)

dataset = load_dataset("hf-internal-testing/librispeech_asr_dummy", "clean", split="validation")
sample = dataset[0]["audio"]

result = pipe(sample, return_timestamps="word")
print(result["chunks"])
```

Note that we **haven't** found the optimal alignment heads for word-level timestamps for `distil-large-v2`, so these word-level timestamps aren't available yet. I'll do some analysis to see what the best configuration is and update the model config accordingly!

**Comment by jasonchanly** [comment]
Hi @sanchit-gandhi can I check if you've found the optimal alignment heads yet for word-level timestamps? Much appreciated!

**Comment by afsara-ben** [comment]
^^same q

**Comment by danieloi** [comment]
will we ever get word-level timestamps for the distilled models? Only sentence-level timestamps seem to be available and i get right now and I get this error when I request word-level timestamps with transformerjs:

Error: Layer index 6 is out of bounds for cross attentions (length 4).
at webpack://@huggingface/transformers/./src/models.js:3498:1
at Array.map ()
at Function._extract_token_timestamps (webpack://@huggingface/transformers/./src/models.js:3496:30)
at Function.generate (webpack://@huggingface/transformers/./src/models.js:3442:1)
at async Function._call_whisper (webpack://@huggingface/transformers/./src/pipelines.js:1867:1)
... message: 'Layer index 6 is out of bounds for cross attentions (length 4).'}

**Comment by afsara-ben** [comment]
@danieloi you can use `whisper-timestamped` library
