### ISSUE TITLE
argument after ** must be a mapping, not NoneType

### ISSUE THREAD

**Issue by Eskaggg** [huggingface/distil-whisper#64]
Hi @sanchit-gandhi 
I have followed the instruction to do the training but in the training section I get the below error. How to fix?
![trainingerror](https://github.com/huggingface/distil-whisper/assets/90891094/7ec4bbd0-8312-4245-b990-359b137c57f3)

**Comment by Eskaggg** [comment]
accelerate launch run_distillation.py \
    --model_name_or_path "./distil-medium-init" \
    --teacher_model_name_or_path "openai/whisper-medium" \
    --train_dataset_name "../common_voice_little_test+../common_voice_little_test" \
    --train_dataset_config_name "mn+mn" \
    --train_split_name "train+test" \
    --text_column_name "sentence+sentence" \
    --train_dataset_samples "10+5" \
    --eval_dataset_name "../common_voice_little_test" \
    --eval_dataset_config_name "mn" \
    --eval_split_name "test" \
    --eval_text_column_name "sentence" \
    --eval_steps 1000 \
    --save_steps 1000 \
    --warmup_steps 50 \
    --learning_rate 0.0001 \
    --lr_scheduler_type "constant_with_warmup" \
    --logging_steps 25 \
    --save_total_limit 1 \
    --max_steps 5000 \
    --wer_threshold 10 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --dataloader_num_workers 8 \
    --preprocessing_num_workers 8 \
    --ddp_timeout 7200 \
    --dtype "fp16" \
    --output_dir "./" \
    --do_train \
    --do_eval \
    --gradient_checkpointing \
    --overwrite_output_dir \
    --predict_with_generate \
    --freeze_encoder \
    --streaming False \
    --push_to_hub

**Comment by sanchit-gandhi** [comment]
Hey @Eskaggg, thanks for reporting! Could you confirm that you've made no changes to the file `create_student_model.py`? And subsequently, what the bash command is that you're using to run this script? e.g. like the template on the README:

```bash
#!/usr/bin/env bash

python create_student_model.py \
  --teacher_checkpoint "openai/whisper-large-v2" \
  --encoder_layers 32 \
  --decoder_layers 2 \
  --save_dir "./distil-large-v2-init"
```

And finally: could you please share the output of this command:

```
transformers-cli env
```

Many thanks!

**Comment by Eskaggg** [comment]
@sanchit-gandhi Tnks for reply 
(output) transformers-cli env:
    - `transformers` version: 4.35.2
    - Platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.31
    - Python version: 3.10.13
    - Huggingface_hub version: 0.19.4
    - Safetensors version: 0.4.1
    - Accelerate version: 0.25.0
    - Accelerate config:    not found
    - PyTorch version (GPU?): 2.1.1+cu121 (True)
    - Tensorflow version (GPU?): not installed (NA)
    - Flax version (CPU?/GPU?/TPU?): not installed (NA)
    - Jax version: not installed
    - JaxLib version: not installed
    - Using GPU in script?: <fill in>
    - Using distributed or parallel set-up in script?: <fill in>

And another error is here:

12/20/2023 11:39:29 - INFO - __main__ - max_steps is given, it will override any value given in num_train_epochs
12/20/2023 11:39:33 - INFO - __main__ - ***** Running training *****
12/20/2023 11:39:33 - INFO - __main__ -   Num examples = 40000
12/20/2023 11:39:33 - INFO - __main__ -   Instantaneous batch size per device = 8
12/20/2023 11:39:33 - INFO - __main__ -   Gradient accumulation steps = 1
12/20/2023 11:39:33 - INFO - __main__ -   Total train batch size (w. parallel & distributed) = 8
12/20/2023 11:39:33 - INFO - __main__ -   Total optimization steps = 5000
Train steps ... :   0%|                                                                                                                          | 0/5000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/codelex/Documents/lawly/linear_regression/distil-whisper/training/Distil-whisper-mn/run_distillation.py", line 1631, in <module>
    main()
  File "/home/codelex/Documents/lawly/linear_regression/distil-whisper/training/Distil-whisper-mn/run_distillation.py", line 1489, in main
    loss, train_metric = train_step(batch, temperature=training_args.temperature)
  File "/home/codelex/Documents/lawly/linear_regression/distil-whisper/training/Distil-whisper-mn/run_distillation.py", line 1357, in train_step
    student_outputs = student_model(**batch)
TypeError: WhisperForConditionalGeneration(
  (model): WhisperModel(
    (encoder): WhisperEncoder(
      (conv1): Conv1d(80, 1280, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv2): Conv1d(1280, 1280, kernel_size=(3,), stride=(2,), padding=(1,))
      (embed_positions): Embedding(1500, 1280)
      (layers): ModuleList(
        (0-15): 16 x WhisperEncoderLayer(
          (self_attn): WhisperAttention(
            (k_proj): Linear(in_features=1280, out_features=1280, bias=False)
            (v_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (q_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
          (final_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): WhisperDecoder(
      (embed_tokens): Embedding(51865, 1280, padding_idx=50257)
      (embed_positions): WhisperPositionalEmbedding(448, 1280)
      (layers): ModuleList(
        (0-1): 2 x WhisperDecoderLayer(
          (self_attn): WhisperAttention(
            (k_proj): Linear(in_features=1280, out_features=1280, bias=False)
            (v_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (q_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (activation_fn): GELUActivation()
          (self_attn_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): WhisperAttention(
            (k_proj): Linear(in_features=1280, out_features=1280, bias=False)
            (v_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (q_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
          (final_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
    )
  )
  (proj_out): Linear(in_features=1280, out_features=51865, bias=False)
) argument after ** must be a mapping, not NoneType

**Comment by Eskaggg** [comment]
And another error is here :

loading file vocab.json
loading file tokenizer.json
loading file merges.txt
loading file normalizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
12/20/2023 11:49:18 - INFO - __main__ - max_steps is given, it will override any value given in num_train_epochs
12/20/2023 11:49:19 - INFO - __main__ - ***** Running training *****
12/20/2023 11:49:19 - INFO - __main__ -   Num examples = 40000
12/20/2023 11:49:19 - INFO - __main__ -   Instantaneous batch size per device = 8
12/20/2023 11:49:19 - INFO - __main__ -   Gradient accumulation steps = 1
12/20/2023 11:49:19 - INFO - __main__ -   Total train batch size (w. parallel & distributed) = 8
12/20/2023 11:49:19 - INFO - __main__ -   Total optimization steps = 5000
Train steps ... :   0%|                                                                                                                          | 0/5000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/codelex/Documents/lawly/linear_regression/distil-whisper/training/Distil-whisper-mn/run_distillation.py", line 1631, in <module>
    main()
  File "/home/codelex/Documents/lawly/linear_regression/distil-whisper/training/Distil-whisper-mn/run_distillation.py", line 1489, in main
    loss, train_metric = train_step(batch, temperature=training_args.temperature)
  File "/home/codelex/Documents/lawly/linear_regression/distil-whisper/training/Distil-whisper-mn/run_distillation.py", line 1357, in train_step
    student_outputs = student_model(**batch)
TypeError: WhisperForConditionalGeneration(
  (model): WhisperModel(
    (encoder): WhisperEncoder(
      (conv1): Conv1d(80, 1280, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv2): Conv1d(1280, 1280, kernel_size=(3,), stride=(2,), padding=(1,))
      (embed_positions): Embedding(1500, 1280)
      (layers): ModuleList(
        (0-31): 32 x WhisperEncoderLayer(
          (self_attn): WhisperAttention(
            (k_proj): Linear(in_features=1280, out_features=1280, bias=False)
            (v_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (q_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
          (final_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): WhisperDecoder(
      (embed_tokens): Embedding(51865, 1280, padding_idx=50257)
      (embed_positions): WhisperPositionalEmbedding(448, 1280)
      (layers): ModuleList(
        (0-1): 2 x WhisperDecoderLayer(
          (self_attn): WhisperAttention(
            (k_proj): Linear(in_features=1280, out_features=1280, bias=False)
            (v_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (q_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (activation_fn): GELUActivation()
          (self_attn_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): WhisperAttention(
            (k_proj): Linear(in_features=1280, out_features=1280, bias=False)
            (v_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (q_proj): Linear(in_features=1280, out_features=1280, bias=True)
            (out_proj): Linear(in_features=1280, out_features=1280, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
          (final_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
    )
  )
  (proj_out): Linear(in_features=1280, out_features=51865, bias=False)
) argument after ** must be a mapping, not NoneType
